version: "3"
services:
#  builder-mingw:
#    build:
#      dockerfile: Dockerfile.mingw
#    volumes:
#      - .:/thingybrowser
#      - ./out:/out
  builder-ubuntu:
    build:
      dockerfile: Dockerfile.ubuntu
    volumes:
      - .:/thingybrowser
      - ./out:/out