version: "3"
services:
  builder-mingw-fedora:
    build:
      dockerfile: building/docker/Dockerfile.fedora.mingw
    volumes:
      - .:/thingybrowser
      - ./out/mingw/fedora:/out
  builder-mingw-ubuntu:
    build:
      dockerfile: building/docker/Dockerfile.ubuntu.mingw
    volumes:
      - .:/thingybrowser
      - ./out/mingw/ubuntu:/out
  builder-ubuntu:
    build:
      dockerfile: building/docker/Dockerfile.ubuntu
    volumes:
      - .:/thingybrowser
      - ./out/ubuntu:/out