version: "3"
services:
  builder-mingw:
    build:
      dockerfile: building/docker/Dockerfile.mingw
    volumes:
      - .:/thingybrowser
      - ./out/mingw:/out
  builder-ubuntu:
    build:
      dockerfile: building/docker/Dockerfile.ubuntu
    volumes:
      - .:/thingybrowser
      - ./out/ubuntu:/out